#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 11 10:04:56 2019

@author: valler
"""

#import os
import xlrd
from statsmodels.tsa.arima_model import ARMA

#print (os.path.abspath('.'))

'''read file and store data in [data]'''
xl_workbook = xlrd.open_workbook('Hawaii.xls')

# List sheet names, and pull a sheet by name
sheet_names = xl_workbook.sheet_names()
xl_sheet = xl_workbook.sheet_by_name(sheet_names[0])
#print('Sheet Names:', sheet_names)

num_cols = xl_sheet.ncols   # Number of columns
num_rows = xl_sheet.nrows   # Number of rows
dataset = [[0]*num_cols for i in range(num_rows)]

data = [[] for i in range(num_rows)]

for row_idx in range(0,xl_sheet.nrows):    # Iterate through rows
    #print ('-'*40)
    #print ('Row: %s' % row_idx)   # Print row number
    for col_idx in range(0, num_cols):  # Iterate through columns
        cell_obj = xl_sheet.cell(row_idx, col_idx)  # Get cell object by row, col
        dataset[row_idx][col_idx]=cell_obj.value
         #print ('Column: [%s] cell_obj: [%s]' % (col_idx, cell_obj))
        if (col_idx == 1):
            data[row_idx]=cell_obj.value
        else :
            continue;



''' fit model'''

del(data[0])
del(data[len(data)-1])     
model = ARMA(data,order=(2,1))  
model_fit = model.fit(disp=True)

yhat = model_fit.predict(len(data), len(data))
